version: '3.8'

services: 
  pgadmin: 
    container_name: pgAdmin
    image: dpage/pgadmin4
    ports: 
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@outlook.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
  
  postgres: 
    container_name: postgres
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: futsal
      




